---
# AWS CCO Rotation Role - Main Tasks
# This role handles all AWS IAM interactions for credential rotation

- name: Get OCP cluster infrastructure (GUID)
  kubernetes.core.k8s_info:
    api_version: config.openshift.io/v1
    kind: Infrastructure
    name: cluster
  register: cluster_infrastructure_info

- name: Extract cluster name from cluster infrastructure
  ansible.builtin.set_fact:
    ocp_cluster_name: "{{ cluster_infrastructure_info.resources[0].status.infrastructureName }}"
  when: cluster_infrastructure_info.resources | length > 0

- name: Fail if cluster name could not be determined
  ansible.builtin.fail:
    msg: "Unable to determine OpenShift cluster infrastructure name"
  when: ocp_cluster_name is not defined

- name: Construct IAM user name
  ansible.builtin.set_fact:
    iam_user_name: "{{ aws_iam_user_prefix }}-{{ ocp_cluster_name }}"

- name: Get current aws-creds secret
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    name: aws-creds
    namespace: kube-system
  register: current_aws_creds_secret

- name: Extract current access key ID from aws-creds secret
  ansible.builtin.set_fact:
    current_access_key_id: "{{ current_aws_creds_secret.resources[0].data.aws_access_key_id | b64decode }}"
  when: 
    - current_aws_creds_secret.resources | length > 0
    - current_aws_creds_secret.resources[0].data.aws_access_key_id is defined

- name: Discovery and cleanup of old IAM user
  block:
    - name: Get all IAM users to find access key owner
      amazon.aws.iam_user_info:
      register: all_iam_users

    - name: Find IAM user associated with current access key
      amazon.aws.iam_access_key_info:
        user_name: "{{ item.user_name }}"
      register: user_access_keys_check
      loop: "{{ all_iam_users.iam_users | default([]) }}"
      loop_control:
        label: "{{ item.user_name }}"
      ignore_errors: true
      
    - name: Set matching user when found
      ansible.builtin.set_fact:
        current_iam_user_name: "{{ item.item.user_name }}"
      loop: "{{ user_access_keys_check.results | default([]) }}"
      loop_control:
        label: "{{ item.item.user_name | default('N/A') }}"
      when:
        - item.access_keys is defined
        - item.access_keys | length > 0
        - current_access_key_id in item.access_keys | map(attribute='access_key_id')
        - not item.failed | default(false)
        - current_iam_user_name is not defined

    - name: Display discovered current IAM user
      ansible.builtin.debug:
        msg: "✅ Found current IAM user {{ current_iam_user_name }} associated with access key"
      when: current_iam_user_name is defined

    - name: Delete old IAM user
      amazon.aws.iam_user:
        name: "{{ current_iam_user_name }}"
        state: absent
      when: current_iam_user_name is defined
      register: old_user_deletion

    - name: Display cleanup of old IAM user
      ansible.builtin.debug:
        msg: "✅ Deleted old IAM user {{ current_iam_user_name }} (will recreate as {{ iam_user_name }})"
      when: 
        - old_user_deletion is defined
        - old_user_deletion.changed

  when: current_access_key_id is defined

- name: Display standardized IAM user that will be used
  ansible.builtin.debug:
    msg: "Will create/use standardized IAM user: {{ iam_user_name }}"

- name: Ensure IAM user exists
  amazon.aws.iam_user:
    name: "{{ iam_user_name }}"
    state: present
  register: iam_user_creation

- name: Display IAM user creation result
  ansible.builtin.debug:
    msg: |-
      {% if iam_user_creation.changed %}
      ✅ Created new IAM user: {{ iam_user_name }}
      {% else %}
      ✅ IAM user already exists: {{ iam_user_name }}
      {% endif %}

- name: Ensure CCO permissions policy is attached to IAM user
  amazon.aws.iam_policy:
    iam_type: user
    iam_name: "{{ iam_user_name }}"
    policy_name: "{{ cco_iam_policy_name }}"
    state: present
    policy_json: "{{ cco_iam_policy_document | to_json }}"

- name: Create new AWS access key for standardized IAM user
  amazon.aws.iam_access_key:
    user_name: "{{ iam_user_name }}"
    state: present
  register: new_aws_creds
  no_log: true

- name: Verify new access key exists
  ansible.builtin.debug:
    msg: "New access key created successfully for user {{ iam_user_name }}"
  when: new_aws_creds.access_key is defined

- name: Base64 encode new AWS credentials
  ansible.builtin.set_fact:
    new_access_key_id_b64: "{{ new_aws_creds.access_key_id | b64encode }}"
    new_secret_access_key_b64: "{{ new_aws_creds.secret_access_key | b64encode }}"
  no_log: true
  